//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCakeMakerASP.NET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CustomerId { get; set; }
        [DisplayName("Họ Và Tên")]
        [Required(ErrorMessage = " Không được để trống !")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Kí tự Lớn hơn 6 và nhỏ hơn 20 ")]
        public string FullName { get; set; }
        [DisplayName("Giới Tính")]
        [Required(ErrorMessage = " Không được để trống !")]
        [StringLength(3, ErrorMessage = "Kí tự Lớn hơn 6 và nhỏ hơn 20 ")]
        public string GenDer { get; set; }
        [DisplayName("Số Điện Thoại")]
        public Nullable<int> Phone { get; set; }
        [DataType(DataType.EmailAddress)]
        
        public string Email { get; set; }
        [DisplayName("Địa Chỉ")]


        [Required(ErrorMessage = " Không được để trống !")]

        public string Address { get; set; }

        [DisplayName("Sinh Nhật")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> Status { get; set; }
        [DisplayName("Mật Khẩu")]
      
        public string Password { get; set; }
        [DisplayName("Tên Đăng Nhập")]
      
        public string Account { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
